### PR TITLE
Add BW Roamer guide

### PR DESCRIPTION
**Pull request by zaksabeast**
# Guide Details

## I want to (select one)

- [x] Add a guide
- [ ] Modify an existing guide

## Games affected

- Black, White

## Type of RNG

Roamers

## Language

English

## Notes

Guide donated by /u/Zapdos44

### CODE REVIEW

**Comment by RichardPaulAstley** [comment]
Just an tip (not sure if you can add this to the guide) : You can trade the roamer from another game. If you're aiming for a Shiny, you don't need to find it and you can just check your Pokedex to see if a Shiny form is registered. If so : win.

**Comment by RichardPaulAstley** [comment]
Always good for people that do retail in the future, since the guide has no indication on retail or emu in the end (could be adapted for both)

**Comment by zaksabeast** [comment]
The guide's name and first line both mention it's for emulators, so Fish's idea is great.

However I agree with Vlad that extra tips would be good for those who choose to adapt this for retail.

**Comment by RichardPaulAstley** [comment]
Yep but I guess EVERY method / tip is really welcome in that kind of case haha

**Comment by zaksabeast** [comment]
I believe that info was actually in the guide.

**Comment by Admiral-Fish** [comment]
On retail you can use ivs + characteristic to narrow down pid

**Pull request merged**
